package:
  name: event-analysis
  version: "1.0.18"

source:
  git_rev: v1.0.18
  git_url: https://github.com/McIntyre-Lab/events.git
  folder: event_analysis

requirements:
  host:
    - python 3.6.*
    - setuptools

  run:
    - python 3.6.*
    - pandas
    - pybedtools 0.7.10.*
    - numpy
    - gffutils 0.9.*

test:
  imports:
    - argparse
    - pandas
    - logging
    - pybedtools
    - sqlite3
    - gffutils
    - glob

about:
  home: https://github.com/McIntyre-Lab/events.git
  license: MIT

