package:
  name: eventAnalysis
  version: "1.0.2"

source:
  git_rev: v1.0.2
  git_url: https://github.com/McIntyre-Lab/events.git
  folder: event_analysis

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - argparse 1.1
    - pandas 0.19.2
    - logging 0.5.1.2
    - pybedtools 0.7.10
    - sqlite3 2.6.0
    - csv
    - numpy
    - gffutils
    - glob
    - Bio
    - collections
    - io
    - openpyxl
    - operator
    - datetime
    - itertools
    - os
    - pysam
    - re
    - sys
    - matplotlib
    - cPickle
    - subprocess
    - vcf

test:
  imports:
    - argparse 1.1
    - pandas 0.19.2
    - logging 0.5.1.2
    - pybedtools 0.7.10
    - sqlite3 2.6.0
    - gffutils
    - glob

about:
  home: https://github.com/McIntyre-Lab/events.git
  license: BSD
  license_file: LICENSE

