package:
  name: event_analysis
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/McIntyre-Lab/events.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:


about:
  home: https://github.com/McIntyre-Lab/events.git
  license: BSD
  license_file: LICENSE

